insert into t_sunso_stock_day_trade_statistic_range_avg_data(
    code,
    name,
    trade_date,
    close_amt,
    close_pre_close_diff_amt_ratio,
    open_pre_close_diff_amt_ratio,
    low_pre_close_diff_amt_ratio,
    high_pre_close_diff_amt_ratio,
    low_high_diff_amt_ratio,

    pre2_avg_close_pre_close_diff_amt_ratio,
    pre2_avg_open_pre_close_diff_amt_ratio,
    pre2_avg_low_pre_close_diff_amt_ratio,
    pre2_avg_high_pre_close_diff_amt_ratio,
    pre2_avg_low_high_diff_amt_ratio,
    pre2_plus_count_close_pre_close_diff_amt_ratio,
    pre2_plus_count_open_pre_close_diff_amt_ratio,
    pre2_plus_count_low_pre_close_diff_amt_ratio,
    pre2_plus_count_high_pre_close_diff_amt_ratio,
    pre2_plus_count_low_high_diff_amt_ratio,

    pre3_avg_close_pre_close_diff_amt_ratio,
    pre3_avg_open_pre_close_diff_amt_ratio,
    pre3_avg_low_pre_close_diff_amt_ratio,
    pre3_avg_high_pre_close_diff_amt_ratio,
    pre3_avg_low_high_diff_amt_ratio,
    pre3_plus_count_close_pre_close_diff_amt_ratio,
    pre3_plus_count_open_pre_close_diff_amt_ratio,
    pre3_plus_count_low_pre_close_diff_amt_ratio,
    pre3_plus_count_high_pre_close_diff_amt_ratio,
    pre3_plus_count_low_high_diff_amt_ratio,


    pre5_avg_close_pre_close_diff_amt_ratio,
    pre5_avg_open_pre_close_diff_amt_ratio,
    pre5_avg_low_pre_close_diff_amt_ratio,
    pre5_avg_high_pre_close_diff_amt_ratio,
    pre5_avg_low_high_diff_amt_ratio,
    pre5_plus_count_close_pre_close_diff_amt_ratio,
    pre5_plus_count_open_pre_close_diff_amt_ratio,
    pre5_plus_count_low_pre_close_diff_amt_ratio,
    pre5_plus_count_high_pre_close_diff_amt_ratio,
    pre5_plus_count_low_high_diff_amt_ratio
)
value(
    '{{code}}',
    '{{name}}',
    '{{trade_date}}',
    {{close_amt}},
    {{close_pre_close_diff_amt_ratio}},
    {{open_pre_close_diff_amt_ratio}},
    {{low_pre_close_diff_amt_ratio}},
    {{high_pre_close_diff_amt_ratio}},
    {{low_high_diff_amt_ratio}},

    {{pre2_avg_close_pre_close_diff_amt_ratio}},
    {{pre2_avg_open_pre_close_diff_amt_ratio}},
    {{pre2_avg_low_pre_close_diff_amt_ratio}},
    {{pre2_avg_high_pre_close_diff_amt_ratio}},
    {{pre2_avg_low_high_diff_amt_ratio}},
    {{pre2_plus_count_close_pre_close_diff_amt_ratio}},
    {{pre2_plus_count_open_pre_close_diff_amt_ratio}},
    {{pre2_plus_count_low_pre_close_diff_amt_ratio}},
    {{pre2_plus_count_high_pre_close_diff_amt_ratio}},
    {{pre2_plus_count_low_high_diff_amt_ratio}},

    {{pre3_avg_close_pre_close_diff_amt_ratio}},
    {{pre3_avg_open_pre_close_diff_amt_ratio}},
    {{pre3_avg_low_pre_close_diff_amt_ratio}},
    {{pre3_avg_high_pre_close_diff_amt_ratio}},
    {{pre3_avg_low_high_diff_amt_ratio}},
    {{pre3_plus_count_close_pre_close_diff_amt_ratio}},
    {{pre3_plus_count_open_pre_close_diff_amt_ratio}},
    {{pre3_plus_count_low_pre_close_diff_amt_ratio}},
    {{pre3_plus_count_high_pre_close_diff_amt_ratio}},
    {{pre3_plus_count_low_high_diff_amt_ratio}},


    {{pre5_avg_close_pre_close_diff_amt_ratio}},
    {{pre5_avg_open_pre_close_diff_amt_ratio}},
    {{pre5_avg_low_pre_close_diff_amt_ratio}},
    {{pre5_avg_high_pre_close_diff_amt_ratio}},
    {{pre5_avg_low_high_diff_amt_ratio}},
    {{pre5_plus_count_close_pre_close_diff_amt_ratio}},
    {{pre5_plus_count_open_pre_close_diff_amt_ratio}},
    {{pre5_plus_count_low_pre_close_diff_amt_ratio}},
    {{pre5_plus_count_high_pre_close_diff_amt_ratio}},
    {{pre5_plus_count_low_high_diff_amt_ratio}}
)
;