CREATE TABLE `t_sunso_stock_day_up_limit_data` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `open_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '开盘价(元)',
  `close_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价(元)',
  `low_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最低价(元)',
  `high_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价(元)',
  `pre_close_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '昨日收盘价(元)',
  `change_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '涨跌幅%',
  `trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '成交量(股)',
  `trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '成交金额(元)' ,
  `turnover_rate` decimal(12,6) NOT NULL DEFAULT -1 COMMENT '换手率',
  `per` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市盈率',
  `pb` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市净率',
  `market_cap_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '总市值(万)',
  `circulation_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '流通市值(万)',
  `up_limit_date` date  NOT NULL COMMENT '涨停日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='每日涨停板股票数据';
create unique index unique_upLimitDate_code on t_sunso_stock_day_up_limit_data(up_limit_date, code);


CREATE TABLE `t_sunso_stock_newly_quotes_data` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `open_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '开盘价(元)',
  `close_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价(元)',
  `low_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最低价(元)',
  `high_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价(元)',
  `avg_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '平均价(元)',
  `pre_close_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '昨日收盘价(元)',
  `turnover_rate` decimal(12,6) NOT NULL DEFAULT -1 COMMENT '换手率',
  `price_change_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '涨跌幅%,今日收盘价-昨日收盘价/昨日收盘价',
  `price_wave_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值(元)',
  `price_wave_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值/昨日收盘价的百分比%',
  `trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '成交量(股)',
  `trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '成交金额(元)' ,
  `avg5_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '近5日平均成交价(元)' ,
  `avg10_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '近10日平均成交价(元)' ,
  `avg20_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '近20日平均成交价(元)' ,
  `avg5_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近5日平均成交量(股)',
  `avg10_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近10日平均成交量(股)',
  `avg20_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近20日平均成交量(股)',
  `avg5_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近5日平均成交金额(元)' ,
  `avg10_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近10日平均成交金额(元)' ,
  `avg20_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近20日平均成交金额(元)' ,
  `inside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '内盘交易量(股)',
  `outside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量(股)',
  `oi_dish_diff_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量-内盘交易量(股)',
  `oi_dish_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易量/内盘交易量的百分比',
  `inside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '内盘交易金额(元)',
  `outside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '外盘交易金额(元)',
  `oi_dish_diff_amt` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易金额-内盘交易金额(元)',
  `oi_dish_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易金额/内盘交易金额的百分比',
  `min_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '小单交易量(手)',
  `mid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '中单交易量(手)',
  `max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '大单交易量(手)',
  `min_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '小单交易金额(元)',
  `mid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '中单交易金额(元)',
  `max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '大单交易金额(元)',
  `first_limit_up_date` varchar(64) DEFAULT NULL COMMENT '第一次涨停时间',
  `first_limit_down_date` varchar(64) DEFAULT NULL COMMENT '第一次跌停时间',
  `per` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市盈率',
  `pb` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市净率',
  `market_cap_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '总市值(万)',
  `circulation_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '流通市值(万)',
  `trade_date` date  NOT NULL COMMENT '交易日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='最新交易日的股票行情数据';
create unique index unique_code_tradeDate on t_sunso_stock_newly_quotes_data(code, trade_date);


CREATE TABLE `t_sunso_stock_newly_quotes_data_hist` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `open_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '开盘价(元)',
  `close_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价(元)',
  `low_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最低价(元)',
  `high_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价(元)',
  `avg_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '平均价(元)',
  `pre_close_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '昨日收盘价(元)',
  `turnover_rate` decimal(12,6) NOT NULL DEFAULT -1 COMMENT '换手率',
  `price_change_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '涨跌幅%,今日收盘价-昨日收盘价/昨日收盘价',
  `price_wave_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值(元)',
  `price_wave_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值/昨日收盘价的百分比%',
  `trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '成交量(股)',
  `trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '成交金额(元)' ,
  `avg5_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近5日平均成交量(股)',
  `avg10_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近10日平均成交量(股)',
  `avg20_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近20日平均成交量(股)',
  `avg5_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近5日平均成交金额(元)' ,
  `avg10_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近10日平均成交金额(元)' ,
  `avg20_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近20日平均成交金额(元)' ,
  `inside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '内盘交易量(股)',
  `outside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量(股)',
  `oi_dish_diff_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量-内盘交易量(股)',
  `oi_dish_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易量/内盘交易量的百分比',
  `inside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '内盘交易金额(元)',
  `outside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '外盘交易金额(元)',
  `oi_dish_diff_amt` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易金额-内盘交易金额(元)',
  `oi_dish_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易金额/内盘交易金额的百分比',
  `min_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '小单交易量(手)',
  `mid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '中单交易量(手)',
  `max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '大单交易量(手)',
  `min_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '小单交易金额(元)',
  `mid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '中单交易金额(元)',
  `max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '大单交易金额(元)',
  `first_limit_up_date` varchar(64) DEFAULT NULL COMMENT '第一次涨停时间',
  `first_limit_down_date` varchar(64) DEFAULT NULL COMMENT '第一次跌停时间',
  `per` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市盈率',
  `pb` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市净率',
  `market_cap_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '总市值(万)',
  `circulation_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '流通市值(万)',
  `trade_date` date  NOT NULL COMMENT '交易日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='最新交易日的历史股票行情数据';
create unique index unique_code_tradeDate on t_sunso_stock_newly_quotes_data_hist(code, trade_date);


drop table t_sunso_stock_all_quotes_data;

CREATE TABLE `t_sunso_stock_all_quotes_data` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `open_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '开盘价(元)',
  `close_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价(元)',
  `low_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最低价(元)',
  `high_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价(元)',
  `avg_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '平均价(元)',
  `pre_close_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '昨日收盘价(元)',
  `turnover_rate` decimal(12,6) NOT NULL DEFAULT -1 COMMENT '换手率',
  `price_change_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '涨跌幅%,今日收盘价-昨日收盘价/昨日收盘价',
  `price_wave_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值(元)',
  `price_wave_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值/昨日收盘价的百分比%',
  `trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '成交量(股)',
  `trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '成交金额(元)' ,
  `avg5_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '近5日平均成交价(元)' ,
  `avg10_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '近10日平均成交价(元)' ,
  `avg20_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '近20日平均成交价(元)' ,
  `avg5_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近5日平均成交量(股)',
  `avg10_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近10日平均成交量(股)',
  `avg20_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近20日平均成交量(股)',
  `avg5_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近5日平均成交金额(元)' ,
  `avg10_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近10日平均成交金额(元)' ,
  `avg20_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近20日平均成交金额(元)' ,
  `inside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '内盘交易量(股)',
  `outside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量(股)',
  `midside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '中间交易量(股)',
  `oi_dish_diff_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量-内盘交易量(股)',
  `oi_dish_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易量/内盘交易量的百分比',
  `inside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '内盘交易金额(元)',
  `outside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '外盘交易金额(元)',
  `midside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '中间盘交易金额(元)',
  `oi_dish_diff_amt` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易金额-内盘交易金额(元)',
  `oi_dish_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易金额/内盘交易金额的百分比',
  `min_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '小单交易量(手)',
  `mid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '中单交易量(手)',
  `max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '大单交易量(手)',
  `sum_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '总交易量(手)',
  `min_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '小单交易量/总交易量的百分比',
  `mid_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '中单交易量/总交易量的百分比',
  `max_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '大单交易量/总交易量的百分比',
  `min_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '小单交易金额(元)',
  `mid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '中单交易金额(元)',
  `max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '大单交易金额(元)',
  `sum_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '总交易金额(元)',
  `min_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '小单交易金额/总交易金额的百分比',
  `mid_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '中单交易金额/总交易金额的百分比',
  `max_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '大单交易金额/总交易金额的百分比',
  `min_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '小单交易次数',
  `mid_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '中单交易次数',
  `max_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '大单交易次数',
  `sum_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '总交易次数',
  `min_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '小单交易次数/总交易次数的百分比',
  `mid_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '中单交易次数/总交易次数的百分比',
  `max_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '大单交易次数/总交易次数的百分比',
  `first_limit_up_time` varchar(64) DEFAULT NULL COMMENT '第一次涨停时间',
  `first_limit_down_time` varchar(64) DEFAULT NULL COMMENT '第一次跌停时间',
  `last_limit_up_time` varchar(64) DEFAULT NULL COMMENT '最后一次涨停时间',
  `last_limit_down_time` varchar(64) DEFAULT NULL COMMENT '最后一次跌停时间',
  `per` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市盈率',
  `pb` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市净率',
  `market_cap_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '总市值(万)',
  `circulation_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '流通市值(万)',
  `trade_date` date  NOT NULL COMMENT '交易日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='所有交易日的股票行情数据';
create unique index unique_code_tradeDate on t_sunso_stock_all_quotes_data(code, trade_date);



CREATE TABLE `t_sunso_stock_day_up_limit_data` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `open_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '开盘价(元)',
  `close_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价(元)',
  `low_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最低价(元)',
  `high_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价(元)',
  `avg_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '平均价(元)',
  `pre_close_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '昨日收盘价(元)',
  `turnover_rate` decimal(12,6) NOT NULL DEFAULT -1 COMMENT '换手率',
  `price_change_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '涨跌幅%,今日收盘价-昨日收盘价/昨日收盘价',
  `price_wave_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值(元)',
  `price_wave_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值/昨日收盘价的百分比%',
  `trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '成交量(股)',
  `trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '成交金额(元)' ,
  `avg5_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近5日平均成交量(股)',
  `avg10_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近10日平均成交量(股)',
  `avg20_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '近20日平均成交量(股)',
  `avg5_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近5日平均成交金额(元)' ,
  `avg10_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近10日平均成交金额(元)' ,
  `avg20_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '近20日平均成交金额(元)' ,
  `inside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '内盘交易量(股)',
  `outside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量(股)',
  `oi_dish_diff_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量-内盘交易量(股)',
  `oi_dish_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易量/内盘交易量的百分比',
  `inside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '内盘交易金额(元)',
  `outside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '外盘交易金额(元)',
  `oi_dish_diff_amt` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易金额-内盘交易金额(元)',
  `oi_dish_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易金额/内盘交易金额的百分比',
  `min_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '小单交易量(手)',
  `mid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '中单交易量(手)',
  `max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '大单交易量(手)',
  `min_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '小单交易金额(元)',
  `mid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '中单交易金额(元)',
  `max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '大单交易金额(元)',
  `first_limit_up_date` varchar(64) DEFAULT NULL COMMENT '第一次涨停时间',
  `first_limit_down_date` varchar(64) DEFAULT NULL COMMENT '第一次跌停时间',
  `per` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市盈率',
  `pb` decimal(12,4)  NOT NULL DEFAULT -1 COMMENT '市净率',
  `market_cap_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '总市值(万)',
  `circulation_amt` decimal(20,8)  NOT NULL DEFAULT -1 COMMENT '流通市值(万)',
  `trade_date` date  NOT NULL COMMENT '交易日期',
  `up_limit_date` date  NOT NULL COMMENT '涨停日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='每日涨停板相关的股票行情数据';
create unique index unique_code_upLimitDate_tradeDate on t_sunso_stock_day_up_limit_data(code, up_limit_date, trade_date);


drop table t_sunso_stock_basic;
CREATE TABLE `t_sunso_stock_basic` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `industry` varchar(128) NOT NULL DEFAULT '' COMMENT '行业',
  `area` varchar(128) NOT NULL DEFAULT '' COMMENT '地区',
  `pe` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '市盈率',
  `pb` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '市净率',
  `earnings_per_share` decimal(12,4) NOT NULL DEFAULT -1 COMMENT '每股收益',
  `net_asset_per_share` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '每股净资产',
  `circulation_stock_volume` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '流通股本(亿)',
  `totals_stock_volume` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '总股本(亿)',
  `totals_stock_amt` decimal(20,6) NOT NULL DEFAULT -1 COMMENT  '总市值(万)',
  `total_assets` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '总资产(万)',
  `liquid_assets` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '流动资产(万)',
  `fixed_assets` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '固定资产(万)',
  `reserved_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '公积金(万)',
  `reserved_amt_per_share` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '每股公积金(元)',
  `un_allot_profit` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '未分配利润(万)',
  `un_allot_profit_per_share` decimal(12,2) NOT NULL DEFAULT -1 COMMENT  '每股未分配利润(元)',
  `income_yy_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收入同比%',
  `profit_yy_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '利润同比%',
  `gross_interest_rate` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '毛利率%',
  `net_profit_rate` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '净利润率%',
  `shareholders` bigint NOT NULL DEFAULT -1 COMMENT '股东人数',
  `time_to_market` bigint(20) NOT NULL DEFAULT -1 COMMENT '上市时间',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index unique_code_tradeDate on t_sunso_stock_basic(code, trade_date);


drop table t_sunso_stock_day_trade_statistic_data;
CREATE TABLE `t_sunso_stock_day_trade_statistic_data` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(32) NOT NULL DEFAULT '' COMMENT '股票代码',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '股票名称',
  `open_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '开盘价(元)',
  `close_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价(元)',
  `low_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最低价(元)',
  `high_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价(元)',
  `avg_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '平均价(元)',
  `close_low_diff_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '收盘价-最低价(元)',
  `high_close_diff_amt` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最高价-收盘价(元)',
  `close_low_diff_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '(收盘价-最低价)/(最高价-最低价)%',
  `high_close_diff_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '(最高价-收盘价)/(最高价-最低价)',
  `pre_close_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '昨日收盘价(元)',
  `trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '成交量(股),直接从当前行情获取数据',
  `trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '成交金额(元)，,直接从当前行情获取数据' ,
  `turnover_rate` decimal(12,6) NOT NULL DEFAULT -1 COMMENT '换手率',
  `price_change_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '涨跌幅%,今日收盘价-昨日收盘价/昨日收盘价',
  `price_wave_amt` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值(元)',
  `price_wave_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '当日最高价与最低价之间的差值/昨日收盘价的百分比%',

  `pre1_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前1日收盘价',
  `pre5_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前5日收盘价',
  `pre10_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前10日收盘价',
  `pre20_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前20日收盘价',
  `pre60_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前60日收盘价',
  `pre90_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前90-日收盘价',
  `pre250_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前250日收盘价',
  `pre365_close_price` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '前365日收盘价',

  `pre1_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前1日收盘价)/前1日收盘价%',
  `pre5_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前5日收盘价)/前5日收盘价%',
  `pre10_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前10日收盘价)/前10日收盘价%',
  `pre20_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前20日收盘价)/前20日收盘价%',
  `pre60_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前60日收盘价)/前60日收盘价%',
  `pre90_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前90日收盘价)/前90-日收盘价%',
  `pre250_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前250日收盘价)/前250日收盘价%',
  `pre365_close_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日收盘价-前365日收盘价)/前365日收盘价%',

  `pre1_low_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日最低价-前1日收盘价)/前1日收盘价%',
  `pre5_low_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日最低价-前5日收盘价)/前5日收盘价%',
  `pre10_low_price_up_down_percent` decimal(12,2)  NOT NULL DEFAULT -1 COMMENT '(当日最低价-前10日收盘价)/前10日收盘价%',

  `pre_avg1_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前1日平均成交价(元)' ,
  `pre_avg5_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前5日平均成交价(元)' ,
  `pre_avg10_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前10日平均成交价(元)' ,
  `pre_avg20_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前20日平均成交价(元)' ,
  `pre_avg60_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前60日平均成交价(元)' ,
  `pre_avg90_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前90日平均成交价(元)' ,
  `pre_avg250_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前250日平均成交价(元)',
  `pre_avg365_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '前365日平均成交价(元)',

  `pre_avg1_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前一日平均成交量(股)',
  `pre_avg5_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前5日平均成交量(股)',
  `pre_avg10_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前10日平均成交量(股)',
  `pre_avg20_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前20日平均成交量(股)',
  `pre_avg60_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前60日平均成交量(股)',
  `pre_avg90_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前90日平均成交量(股)',
  `pre_avg250_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前250日平均成交量(股)',
  `pre_avg365_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '前365日平均成交量(股)',

  `pre_avg1_trade_amt` bigint NOT NULL DEFAULT -1  COMMENT '前一日平均成交金额(元)',
  `pre_avg5_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前5日平均成交金额(元)' ,
  `pre_avg10_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前10日平均成交金额(元)' ,
  `pre_avg20_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前20日平均成交金额(元)' ,
  `pre_avg60_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前60日平均成交金额(元)' ,
  `pre_avg90_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前90日平均成交金额(元)' ,
  `pre_avg250_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前250日平均成交金额(元)' ,
  `pre_avg365_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '前365日平均成交金额(元)' ,

  `inside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '内盘交易量(股)',
  `outside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量(股)',
  `midside_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '中间交易量(股)',
  `sum_dish_volume` bigint NOT NULL DEFAULT -1  COMMENT '总交易量(股)',
  `oi_dish_diff_volume` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易量-内盘交易量(股)',
  `oi_dish_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易量/内盘交易量的百分比',
  `inside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '内盘交易金额(元)',
  `outside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '外盘交易金额(元)',
  `midside_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '中间盘交易金额(元)',
  `sum_dish_amt` decimal(18,0) NOT NULL DEFAULT -1  COMMENT '总交易金额(元)',
  `oi_dish_diff_amt` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易金额-内盘交易金额(元)',
  `oi_dish_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易金额/内盘交易金额的百分比',
  `inside_dish_count` bigint NOT NULL DEFAULT -1  COMMENT '内盘交易次数',
  `outside_dish_count` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易次数',
  `midside_dish_count` bigint NOT NULL DEFAULT -1  COMMENT '中间盘交易次数',
  `sum_dish_count` bigint NOT NULL DEFAULT -1  COMMENT '总交易次数',
  `oi_dish_diff_count` bigint NOT NULL DEFAULT -1  COMMENT '外盘交易次数-内盘交易次数',
  `oi_dish_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '外盘交易次数/内盘交易次数的百分比',

  `min_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '小单交易量(手)',
  `mid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '中单交易量(手)',
  `max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '大单交易量(手)',
  `super_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '超级大单交易量(手)',
  `sum_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '总交易量(手)',
  `min_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '小单交易量/总交易量的百分比',
  `mid_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '中单交易量/总交易量的百分比',
  `max_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '大单交易量/总交易量的百分比',
  `super_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '超级大单交易量/总交易量的百分比',
  `min_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '小单交易金额(元)',
  `mid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '中单交易金额(元)',
  `max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '大单交易金额(元)',
  `super_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '超级大单交易金额(元)',
  `sum_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '总交易金额(元)',
  `min_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '小单交易金额/总交易金额的百分比',
  `mid_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '中单交易金额/总交易金额的百分比',
  `max_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '大单交易金额/总交易金额的百分比',
  `super_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '超级大单交易金额/总交易金额的百分比',
  `min_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '小单交易次数',
  `mid_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '中单交易次数',
  `max_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '大单交易次数',
  `super_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '超级大单交易次数',
  `sum_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '总交易次数',
  `min_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '小单交易次数/总交易次数的百分比',
  `mid_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '中单交易次数/总交易次数的百分比',
  `max_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '大单交易次数/总交易次数的百分比',
  `super_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '超级大单交易次数/总交易次数的百分比',

  `max_trade_distribution_time` varchar(10000) DEFAULT '' COMMENT '大单分布时间',
  `super_trade_distribution_time` varchar(10000) DEFAULT '' COMMENT '超级大单分布时间',

  `single_max_buy_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '单笔最大买单交易数量(手)',
  `single_max_buy_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '单笔最大买单交易金额(元)' ,
  `single_max_buy_trade_time` varchar(64) NOT NULL DEFAULT '' COMMENT '单笔最大买单交易时间',
  `single_max_sell_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '单笔最大卖单交易数量(手)',
  `single_max_sell_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '单笔最大卖单交易金额(元)' ,
  `single_max_sell_trade_time` varchar(64) NOT NULL DEFAULT '' COMMENT '单笔最大卖单交易时间',
  `single_max_buy_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最大买单数量/总交易数量的百分比',
  `single_max_buy_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最大买单金额/总交易金额的百分比',
  `single_max_sell_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最大卖单数量/总交易数量的百分比',
  `single_max_sell_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '最大卖单金额/总交易金额的百分比',

  `early_before_min_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘前部分最小交易价格',
  `early_before_max_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘前部分最大交易价格',
  `early_before_avg_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘前部分平均交易价格',
  `early_before_diff_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘前部分最大交易价格-早盘前部分最小交易价格',
  `early_after_min_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘后部分最小交易价格',
  `early_after_max_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘后部分最大交易价格',
  `early_after_avg_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘后部分平均交易价格',
  `early_after_diff_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '早盘后部分最大交易价格-早盘后部分最小交易价格',
  `noon_before_min_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘前部分最小交易价格',
  `noon_before_max_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘前部分最大交易价格',
  `noon_before_avg_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘前部分平均交易价格',
  `noon_before_diff_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘前部分最大交易价格-午盘前部分最小交易价格',
  `noon_after_min_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘后部分最小交易价格',
  `noon_after_max_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘后部分最大交易价格',
  `noon_after_avg_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘后部分平均交易价格',
  `noon_after_diff_trade_price` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '午盘后部分最大交易价格-午盘后部分最小交易价格',

  `early_before_max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分大额交易数量(手)',
  `early_before_max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '早盘前部分大额交易金额(元)' ,
  `early_before_max_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '单早盘前部分大额交易次数(手)',
  `early_before_buy_max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分买入大额交易数量(手)',
  `early_before_buy_max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '早盘前部分买入大额交易金额(元)' ,
  `early_before_buy_max_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分买入大额交易次数(手)',
  `early_before_sell_max_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分卖出大额交易数量(手)',
  `early_before_sell_max_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '早盘前部分卖出大额交易金额(元)' ,
  `early_before_sell_max_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分卖出大额交易次数(手)',
  `early_before_bs_max_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1   COMMENT '早盘前部分买入大额交易数量/早盘前部分卖出大额交易数量%',
  `early_before_bs_max_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1  COMMENT '早盘前部分买入大额交易金额/早盘前部分卖出大额交易金额%' ,
  `early_before_bs_max_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1  COMMENT '早盘前部分买入大额交易次数/早盘前部分卖出大额交易次数%',
  `early_before_super_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分超级大额交易数量(手)',
  `early_before_super_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '早盘前部分超级大额交易金额(元)' ,
  `early_before_super_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '单早盘前部分超级大额交易次数(手)',
  `early_before_buy_super_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分买入超级大额交易数量(手)',
  `early_before_buy_super_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '早盘前部分买入超级大额交易金额(元)' ,
  `early_before_buy_super_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分买入超级大额交易次数(手)',
  `early_before_sell_super_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分卖出超级大额交易数量(手)',
  `early_before_sell_super_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '早盘前部分卖出超级大额交易金额(元)' ,
  `early_before_sell_super_trade_count` bigint NOT NULL DEFAULT -1  COMMENT '早盘前部分卖出超级大额交易次数(手)',
  `early_before_bs_super_trade_volume_percent` decimal(12,2) NOT NULL DEFAULT -1   COMMENT '早盘前部分买入超级大额交易数量/早盘前部分卖出超级大额交易数量%',
  `early_before_bs_super_trade_amt_percent` decimal(12,2) NOT NULL DEFAULT -1  COMMENT '早盘前部分买入超级大额交易金额/早盘前部分卖出超级大额交易金额%' ,
  `early_before_bs_super_trade_count_percent` decimal(12,2) NOT NULL DEFAULT -1  COMMENT '早盘前部分买入超级大额交易次数/早盘前部分卖出超级大额交易次数%',


  `open_bid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '开盘集合竞价的交易量(手)',
  `open_bid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '开盘集合竞价的金额(元)',
  `close_bid_trade_volume` bigint NOT NULL DEFAULT -1  COMMENT '收盘集合竞价的交易量(手)',
  `close_bid_trade_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '收盘集合竞价的金额(元)',
  `limit_up_volume` bigint NOT NULL DEFAULT -1  COMMENT '涨停交易量(手)',
  `limit_up_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '涨停交易金额(元)',
  `limit_down_volume` bigint NOT NULL DEFAULT -1  COMMENT '跌停交易量(手)',
  `limit_down_amt` decimal(18,0) NOT NULL DEFAULT -1 COMMENT '跌停交易金额(元)',
  `first_limit_up_time` varchar(64) DEFAULT NULL COMMENT '第一次涨停时间',
  `first_limit_down_time` varchar(64) DEFAULT NULL COMMENT '第一次跌停时间',
  `last_limit_up_time` varchar(64) DEFAULT NULL COMMENT '最后一次涨停时间',
  `last_limit_down_time` varchar(64) DEFAULT NULL COMMENT '最后一次跌停时间',

  `continue_up_down_days` bigint NOT NULL DEFAULT -1  COMMENT '已连续涨跌的次数',
  `contiune_up_down_percent` decimal(12,2) NOT NULL DEFAULT -1 COMMENT '已连续涨跌的幅度比例',

  `trade_date` date  NOT NULL COMMENT '交易日期',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='最新交易日的股票交易统计数据';
create unique index unique_code_tradeDate on t_sunso_stock_day_trade_statistic_data(code, trade_date);